# Generated by Django 3.0.4 on 2020-05-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mutable',
            field=models.BooleanField(default=True),
        ),
    ]
