# Generated by Django 3.0.4 on 2020-06-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_mutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owned',
            field=models.BooleanField(default=False),
        ),
    ]
