# Generated by Django 3.0.4 on 2020-06-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_owned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owned',
            new_name='private',
        ),
    ]
