# Generated by Django 3.0.4 on 2020-06-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
    ]
