# Generated by Django 3.0.4 on 2020-06-25 16:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), blank=True, null=True, size=None),
        ),
    ]
