# Generated by Django 3.0.4 on 2020-06-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200625_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='branch',
            field=models.CharField(default='master', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='repo',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
