# Generated by Django 3.0.4 on 2020-06-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200627_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='desc',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
