# Generated by Django 3.0.4 on 2020-06-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_recipe_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='raw_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
