# Generated by Django 3.0.4 on 2020-06-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200628_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='raw_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='repo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
