# Generated by Django 3.0.4 on 2020-07-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200628_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='url_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
