# Generated by Django 3.0.4 on 2020-07-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200701_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='url_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
