# Generated by Django 4.0.4 on 2022-08-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.SmallIntegerField(default='1'),
        ),
    ]
